# Get base ubuntu docker image
FROM condaforge/miniforge3:25.3.0-3

# Install and update packages
RUN mamba install \
    -c conda-forge \
    -c bioconda \
    --yes \
    checkm2=1.1.0 \
    && mamba clean -afy \
    && mkdir -p workdir/input \
    && mkdir workdir/output \
    && mkdir workdir/bin \
    && mkdir workdir/database

# Copy in running script with permissions
COPY --chmod=0755 lib/bacass_qc.sh /workdir/bin
COPY --chmod=0755 lib/qc_db_install.sh /workdir/bin

# Add bin directory to path
ENV PATH="$PATH:/workdir/bin"
