# Get base ubuntu docker image
FROM condaforge/miniforge3:24.3.0-0

# Install and update packages
RUN mamba install \
    -c conda-forge \
    -c bioconda \
    --yes \
    --freeze-installed \
    python=3.10 \
    bakta=1.9.4 \
    genomad=1.8.0 \
    && conda clean -afy \
    && mkdir -p workdir/database \
    && mkdir workdir/bin

# Copy in running script with permissions
COPY --chmod=0755 lib/db_install.sh /workdir/bin

# Add bin directory to path and set working directory
ENV PATH="$PATH:/workdir/bin"
WORKDIR /workdir/database
